export const COMPANIES = [
  'SONATRACH',
  'NAFTAL',
  'Algérie Télécom',
  'CNAS',
  'CASNOS',
  'CNAC',
  'Air Algérie',
  'COSIDER',
  'SONELGAZ',
  'CACOBATPH',
  'Mobilis',
  'GICA'
];

export const BANKS = [
  'BNA',
  'BEA',
  'BADR',
  'CPA',
  'BDL',
  'BARAKA',
  'CNEP',
  'SGA',
  'AGB',
  'BNP Paribas',
  'Trust Bank',
  'HSBC'
];

export const MENU_PAGES = [
  { path: '/dashboard', label: 'Interface de suivi', icon: 'LayoutDashboard' },
  { path: '/virement', label: 'Virement bancaire', icon: 'Send' },
  { path: '/cheques-impayes', label: 'Chèques impayés', icon: 'FileX' },
  { path: '/fraude-ia', label: 'Détection fraude IA', icon: 'Shield' },
  { path: '/mourabaha', label: 'Finance islamique Mourabaha', icon: 'Landmark' },
  { path: '/releves', label: 'Relevés', icon: 'FileText' },
  { path: '/oppositions', label: 'Oppositions', icon: 'Ban' },
  { path: '/atd', label: 'ATD', icon: 'AlertCircle' },
  { path: '/contrats', label: 'Contrats', icon: 'FileSignature' },
  { path: '/factures', label: 'Factures', icon: 'Receipt' },
  { path: '/echeancier', label: 'Échéancier crédits', icon: 'Calendar' },
  { path: '/alertes', label: 'Alertes personnalisées', icon: 'Bell' },
  { path: '/beneficiaires', label: 'Bénéficiaires fréquents', icon: 'Users' },
  { path: '/historique', label: 'Historique complet', icon: 'History' },
  { path: '/litiges', label: 'Litiges', icon: 'Scale' },
  { path: '/audit', label: 'Rapports audit', icon: 'FileSearch' },
  { path: '/droits', label: 'Gestion droits', icon: 'UserCog' },
  { path: '/tresorerie', label: 'Trésorerie prévisionnelle', icon: 'TrendingUp' },
  { path: '/correspondants', label: 'Correspondants', icon: 'Building' },
  { path: '/taux-change', label: 'Taux change', icon: 'Currency' },
  { path: '/documents', label: 'Documents partagés', icon: 'FolderOpen' },
  { path: '/statistiques', label: 'Statistiques usage', icon: 'BarChart' },
  { path: '/parametres', label: 'Paramètres', icon: 'Settings' },
  { path: '/garanties', label: 'Garanties bancaires', icon: 'ShieldCheck' },
  { path: '/lettres-credit', label: 'Lettres de crédit', icon: 'Mail' },
  { path: '/effets-commerce', label: 'Effets de commerce', icon: 'CreditCard' },
  { path: '/conciliation', label: 'Conciliation bancaire', icon: 'GitCompare' },
  { path: '/cartes', label: 'Gestion cartes professionnelles', icon: 'Wallet' },
  { path: '/remises', label: 'Remises chèques', icon: 'Upload' },
  { path: '/international', label: 'Opérations internationales', icon: 'Globe' },
];
